[2024-11-13T02:57:43.868+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: DAG_Model_Training_and_Evaluation.train_and_predict_task manual__2024-11-13T02:57:41.956081+00:00 [queued]>
[2024-11-13T02:57:43.874+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: DAG_Model_Training_and_Evaluation.train_and_predict_task manual__2024-11-13T02:57:41.956081+00:00 [queued]>
[2024-11-13T02:57:43.874+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-13T02:57:43.874+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-13T02:57:43.875+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-13T02:57:43.893+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): train_and_predict_task> on 2024-11-13 02:57:41.956081+00:00
[2024-11-13T02:57:43.898+0000] {standard_task_runner.py:55} INFO - Started process 163 to run task
[2024-11-13T02:57:43.900+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DAG_Model_Training_and_Evaluation', 'train_and_predict_task', 'manual__2024-11-13T02:57:41.956081+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/modeling_and_eval_dag.py', '--cfg-path', '/tmp/tmp57mc82l9']
[2024-11-13T02:57:43.902+0000] {standard_task_runner.py:83} INFO - Job 275: Subtask train_and_predict_task
[2024-11-13T02:57:43.966+0000] {task_command.py:388} INFO - Running <TaskInstance: DAG_Model_Training_and_Evaluation.train_and_predict_task manual__2024-11-13T02:57:41.956081+00:00 [running]> on host b77d411e2e76
[2024-11-13T02:57:44.024+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=House_Price_Prediction Team
AIRFLOW_CTX_DAG_ID=DAG_Model_Training_and_Evaluation
AIRFLOW_CTX_TASK_ID=train_and_predict_task
AIRFLOW_CTX_EXECUTION_DATE=2024-11-13T02:57:41.956081+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-13T02:57:41.956081+00:00
[2024-11-13T02:57:44.044+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/modeling_and_eval_dag.py", line 38, in train_and_predict_callable
    augmented_data = pd.read_json(augmented_data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 465, in dict_to_mgr
    arrays, data_names, index, columns, dtype=dtype, typ=typ, consolidate=copy
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
[2024-11-13T02:57:44.053+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=DAG_Model_Training_and_Evaluation, task_id=train_and_predict_task, execution_date=20241113T025741, start_date=20241113T025743, end_date=20241113T025744
[2024-11-13T02:57:44.070+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 275 for task train_and_predict_task (All arrays must be of the same length; 163)
[2024-11-13T02:57:44.084+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-13T02:57:44.141+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
