[2024-11-04T00:42:48.174+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: DAG_Data_Preprocessing.feature_selection_task manual__2024-11-04T00:37:32.241116+00:00 [queued]>
[2024-11-04T00:42:48.180+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: DAG_Data_Preprocessing.feature_selection_task manual__2024-11-04T00:37:32.241116+00:00 [queued]>
[2024-11-04T00:42:48.180+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T00:42:48.180+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-11-04T00:42:48.180+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T00:42:48.186+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): feature_selection_task> on 2024-11-04 00:37:32.241116+00:00
[2024-11-04T00:42:48.191+0000] {standard_task_runner.py:55} INFO - Started process 730 to run task
[2024-11-04T00:42:48.193+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DAG_Data_Preprocessing', 'feature_selection_task', 'manual__2024-11-04T00:37:32.241116+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpn18m16p4']
[2024-11-04T00:42:48.194+0000] {standard_task_runner.py:83} INFO - Job 198: Subtask feature_selection_task
[2024-11-04T00:42:48.269+0000] {task_command.py:388} INFO - Running <TaskInstance: DAG_Data_Preprocessing.feature_selection_task manual__2024-11-04T00:37:32.241116+00:00 [running]> on host b77d411e2e76
[2024-11-04T00:42:48.325+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=House_Price_Prediction Team
AIRFLOW_CTX_DAG_ID=DAG_Data_Preprocessing
AIRFLOW_CTX_TASK_ID=feature_selection_task
AIRFLOW_CTX_EXECUTION_DATE=2024-11-04T00:37:32.241116+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-04T00:37:32.241116+00:00
[2024-11-04T00:42:48.494+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflowdag.py", line 191, in feature_selection_callable
    final_features = rank_features_by_lasso(encoded_data_json, selected_features, target, threshold=0.1)
TypeError: rank_features_by_lasso() got an unexpected keyword argument 'threshold'
[2024-11-04T00:42:48.500+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=DAG_Data_Preprocessing, task_id=feature_selection_task, execution_date=20241104T003732, start_date=20241104T004248, end_date=20241104T004248
[2024-11-04T00:42:48.506+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 198 for task feature_selection_task (rank_features_by_lasso() got an unexpected keyword argument 'threshold'; 730)
[2024-11-04T00:42:48.541+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-04T00:42:48.555+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
